classDiagram 
	
	class IEmployeeRepository  {
		-DeleteEmployee(int EmployeeId) void
		-AddEmployee(Employee employee) int
		-GetEmployeesByPositionId(int positionId) IQueryable~Employee~
		-GetEmployeeById(int employeeId) Employee
		+GetAllPositions() IQueryable~Position~
	}
	class Child  {
		+ Id : int
		+ Name : string
		+ LastName : string
		+ BirthDate : DateTime
		+ Address : string
		+ Nationality : string
		+ PESEL : string
		+ ParentPhoneNumber : string
		+ ParentNames : string
		+ GroupId : int
		+ Group : Group
		+ Declarations : ICollection~Declaration~
	}
	class Position  {
		+ Id : int
		+ Name : string
		+ Category : string
		+ Employees : ICollection~Employee~
	}
	class Education  {
		+ EducationId : int
		+ Name : string
		+ Description : string
		+ Type : string
		+ Employees : ICollection~Employee~
	}
	class Teacher  {
		+ TypeTeacher : string
		+ IsDirector : bool
		+ PensumHours : int
		+ Group : Group
	}
	class Group  {
		+ Id : int
		+ GroupName : string
		+ CurrentChildrenCount : int
		+ GirlsCount : int
		+ BoysCount : int
		+ MaxChildrenCount : int
		+ TeacherId : int
		+ Children : ICollection~Child~
		+ Teacher : Teacher
	}
	class Employee  {
		+ Id : int
		+ Name : string
		+ LastName : string
		+ WorkingHours : double
		+ EmploymentDate : DateTime
		+ IsActive : bool
		+ PositionId : int
		+ Position : Position
		+ Educations : ICollection~Education~
	}
	class Declaration  {
		+ Id : int
		+ ChildId : int
		+ Child : Child
		+ Type : string
		+ IssueDate : DateTime?
		+ ValidUntil : DateTime?
		+ IssuingAuthority : string
		+ Diagnosis : string
		+ IsVoluntaryRequest : bool
		+ Description : string
	}
	
	Teacher --|> Employee
	